### ISSUE TITLE
/datasets

### ISSUE THREAD

**Issue by jchuahtacc** [DemocratizingData/democratizingdata-api#10]
- [x] /datasets
- [x] /datasets/{parent_alias_id}/aliases
- [x] /datasets/{parent_alias_id}/publications
- [x] /datasets/{parent_alias_id}/topics
- [x] /datasets/{parent_alias_id}/authors

**Comment by happycodemonkey** [comment]
datasets endpoints implemented in endpoint-devel, merged with dev and pushed up for peer reivew
