### ISSUE TITLE
Have PPRD environment visible to users without VPN access.

### ISSUE THREAD

**Issue by NotChristianGarcia** [DemocratizingData/democratizingdata-api#33]
Currently we have to stage data changes in prod for our users to QA. This of course causes a situation where we're deploying and editing prod. I propose removing VPN access as a requirement to reaching pprd.democratizing-data.tacc.utexas.edu/.

**Comment by kevinpricethesecond** [comment]
Ticket created -> https://tickets.tacc.utexas.edu/Ticket/Display.html?id=24973

**Comment by kevinpricethesecond** [comment]
Ticket closed
